.travis.yml

Upgrade to the new container-based infrastructure on Travis CI.

travis: container-based infrastructure

---

lib/make-middleware.js
test/issue-232.js

lib: always report limit errors

---

README-zh-cn.md
README.md
doc/README-zh-cn.md

add chinese language readme.md, to let chinese better use this project , tks

add chinese language readme.md

---

README.md
doc/README-zh-cn.md

Add link to ko version from zh-CN & en.
Fix some wording and add description for "preservePath" in zh-CN

Patch the README file.

---

package.json

Bump concat-stream to at least 1.5.2

---

doc/README-zh-cn.md

change README-zh-cn.md from GBK to UTF-8

---

README.md

I think adding the enctype="multipart/form-data" to the form isn't something a beginner programmer knows about. This might improve the experience of using Multer and reduce issues being raised.

Explanation for beginner programmers

---

README.md

I am not sure, but it seems better with this, to avoid entering in the wrong branchment (`an unknown error occured when uploading`) when everything wents fine ?

(not sure) Fix a logical branchment in the readme

---

doc/README-zh-cn.md

Fix broken link in Chinese Readme

Fix broken link in Chinese Readme

---

doc/README-ru.md

Fix mistake

---

README.md

Add unit for fieldSize in busboy limit params

---

README.md

Fixes: https://github.com/expressjs/multer/issues/197
cc @LinusU

doc: clarify the callback calling convention

---

storage/disk.js

Fixes: https://github.com/expressjs/multer/issues/509
Fixes: https://github.com/expressjs/multer/issues/811
cc @LinusU

storage: replace deprecated pseudoRandomBytes with randomBytes

---

doc/README-es.md

+ Added file as /doc/README-es.md
I hope it will be usefull.
Let me know if you want any kind of changes.

Added spanish translation of README.md

---

README.md

This addresses https://github.com/expressjs/multer/issues/579#issuecomment-381947094

updated readme with example on how to link to html multipart form

---

README.md
doc/README-vi.md

I translated to Vietnamese, hope it helps!

add vietnamese language README.md

---

doc/README-ko.md
doc/README-pt-br.md

Update in Readme-pt-br and fix in Readme-ko

Update in Readme-pt-br and fix in Readme-ko

---

.github/workflows/ci.yml
package.json

With that, CI should work on the LTS branch

add ci to lts branch

---

.github/workflows/codeql.yml
.github/workflows/scorecard.yml
.travis.yml
README.md
doc/README-ar.md
doc/README-es.md
doc/README-fr.md
doc/README-ko.md
doc/README-pt-br.md
doc/README-ru.md
doc/README-uz.md
doc/README-vi.md
doc/README-zh-cn.md
package.json

master -> v2

---

doc/README-ar.md
doc/README-es.md
doc/README-fr.md
doc/README-ko.md
doc/README-pt-br.md
doc/README-ru.md
doc/README-uz.md
doc/README-vi.md
doc/README-zh-cn.md

📝 fix badges in translation files

---

.github/workflows/ci.yml
README.md
doc/README-ar.md
doc/README-es.md
doc/README-fr.md
doc/README-ko.md
doc/README-pt-br.md
doc/README-ru.md
doc/README-uz.md
doc/README-vi.md
doc/README-zh-cn.md

♻️ use version tag for CI, fix CI badge, fix references to master/main
