expressjs/multer

- README.md
"Changed the grammar on line 142 by adding an 'and' after the penultimate element in the list, by adding two commas, and by changing the 'are' to 'is' for referencing the file object. I believe this makes the documentation more readable and avoids a little confusion."
> Grammar changes to the onFileUploadStart function documentation.

- lib/make-middleware.js
- package.json
- test/express-integration.js
Trying to track down the bug in #168
To run tests from this branch:
```sh
git clone https://github.com/expressjs/multer.git
cd multer
git checkout express-integration-test
npm install
npm test
```
> [WIP] test: express integration

- lib/make-middleware.js
- package.json
- test/_util.js
- test/express-integration.js
This should hopefully fix a number of bugs where multer/the browser appears to hang.
I'm waiting on @mscdex comment in nodejs/node#2325 before merging thought, I might be fucking up something important.
Test this fix by installing as such:
```sh
npm install expressjs/multer#d787546
```
> lib: work around node.js bug

- README.md
- index.js
- test/expected-files.js
Allows the receiving of files regardless of their fieldname.
I'm still not sure if we should merge this. @jpfluger, @hacksparrow, what are your thoughts?
> lib: option to allow any file

- StorageEngine.md
MyCustomStorage constructor had an attribution to opts object, which was absolutely wrong, since we would like to access getDestination as a method of MyCustomStorage in line 51. Hence the right statement is assigning the value to 'this' which represents the object itself.
> Change line 47 for correctness

- README.md
- index.js
- lib/file-appender.js
- test/none.js
Implementation of #278.
Usage example:
```javascript
var express = require('express')
var multer  = require('multer')
var upload = multer({ dest: 'uploads/' })
var app = express()
app.post("/just-data", upload.none(), function (req, res) {
// req.body will hold the text fields, if there were any
// err expected in case of a file upload (https://github.com/expressjs/multer#error-handling)
})
```
> Closes #278

- lib/make-middleware.js
- test/error-handling.js
When you have an upload that has more than one error, seemingly only with disk storage, it causes the node process to crash. More details here - https://github.com/expressjs/multer/issues/335
```
Uncaught TypeError: path must be a string
```
Tests should showcase an example of this, along with a potential fix.
> Prevent Multiple Errors from Crashing

- README.md
- index.js
- lib/make-middleware.js
I'm working on a cloud compiler service that allows uploading files from a directory tree so it needs access to the entire path of each file that a user uploads.
There's a `preservePath` option in Busboy but it's not exposed in Multer so I added an option to Multer to allow preserving paths for uploaded files.
> Pass the preservePath down to Busboy

- doc/README-ko.md
Translated the Multer README.md in Korean.
It locates under doc/ folder with the name `README-ko.md` according to ISO 639-1 standard language code.
> Add a Readme file in Korean

- storage/memory.js
- test/memory-storage.js
Resolves issue #667 which is also discussed in #461
> Force req.file.buffer to always be a Buffer

- package.json
Version 1.0.0 of testdata-w3c-json-form contains a correction to the
test data. Without the correction (of the bottle-on-wall type from an
array of numbers to an array of strings), it is possible that tests will
break in Node.js 13.0.0 or a future release.
> chore: Update testdata-w3c-json-form

- README.md
I was encountering an issue where two files had the same name due to being handled in the same millisecond. While not a bug, adding extra uniqueness may save someone else time troubleshooting 'missing' files.
> Add Math.random() to storage filename example

- lib/make-middleware.js
- lib/multer-error.js
- package.json
- test/disk-storage.js
- test/error-handling.js
- test/expected-files.js
- test/express-integration.js
- test/fields.js
- test/file-filter.js
- test/file-ordering.js
- test/functionality.js
- test/issue-232.js
- test/memory-storage.js
- test/none.js
- test/reuse-middleware.js
- test/select-field.js
- test/unicode.js
This upgrades `standard` which resolves the CI issue on Node.js 4. Of course some rules changes, especially around `assert` usage, so I made what seemed like the minimal changes for it. Since `assert.deepEqual` is deprecated and `assert.deepStrictEqual` does not exist on Node.js 0.10, I pulled in `deep-equal` so the tests were still nice and readable.
> package: bump standard

- package.json
A new version of [mkdirp's 0.x](https://github.com/isaacs/node-mkdirp/pull/15) line has fixed the https://github.com/expressjs/multer/issues/139 infinite loop on windows issue
I do not know what the deal is with the one failing test on CI
> bump mkdirp version

- README.md
- doc/README-es.md
- doc/README-ko.md
- doc/README-pt-br.md
- doc/README-ru.md
- doc/README-zh-cn.md
Update `var` to `const` in Readme and all translations. This was done with a search replace on each document, I believe but did not verify that all code examples are the same in all translations. 
Interestingly though, I think the English readme might have an extra codeblock that the others don't. Someone should check the blame and see if we need to update the translations with an example. Although I guess we would then need to translate that example haha. 
Edit: [Found it](https://github.com/expressjs/multer/pull/580) and it's of course something I reviewed. Looking back at it, I'm not sure that example was necessary. I think it just repeats the example above it. Maybe the elaborated explanation should get moved up.
closes #1012
> doc: update var to const in all Readmes

- README.md
- doc/README-es.md
- doc/README-ko.md
- doc/README-pt-br.md
- doc/README-ru.md
- doc/README-zh-cn.md
Fixed typos and improved Spanish docs.
Add Spanish (Español) to README.md and other docs.
Fixed typos in Brazilian Portuguese in Translations.
Fixed other's language's docs Translations by translating Brazilian Portuguese to each docs language.
Organize the hierachy of the Translations on each docs based on README.md
> docs: Fixes multiple misspellings and typos, improves Spanish translation

- lib/make-middleware.js
- lib/multer-error.js
- test/error-handling.js
Without this fix fields without a name result in a "TypeError: Cannot read property 'length' of undefined"
in the underlying append-field library.
The current change allows getting an error from multer that makes it
possible to handle it in servers.
See expressjs/multer#553
> Fixes expressjs/multer#553 . Makes multer handle missing field names.

- README.md
- doc/README-ar.md
- doc/README-ko.md
- doc/README-ru.md
- doc/README-zh-cn.md
PR for issue #763 
What's changed:
* Translated full Readme.md to Arabic  
* Add correct link to all README files
> add Arabic translation for README .. 

- README.md
Update the link for the "Node.js error handling" blog post to the archived version as suggested by @LinusU 🫡
Thanks to all the contributors 🙌
> Update README.md to fix issue #1114

- doc/README-pt-br.md
Here is my contribution to improve the translation of the readme into Brazilian Portuguese
> Improve the Brazilian Portuguese translation

- doc/README-pt-br.md
Fix a issue with pt-br readme
English link was linking to russian documentation
> Fix a mistake with README-pt-br.md

- test/express-integration.js
Cheery picks the test from the `lts` branch to `master`
> test: add test for out-of-band error event

- .github/workflows/ci.yml
> ci: use `ubuntu-latest` as default runner

- .github/workflows/ci.yml
https://github.com/expressjs/multer/pull/1308 solves the pipeline initialization issue
> ci: add support for Node@23 and Node@24

- CHANGELOG.md
multer 1.4.4-lts.1 upgraded busboy to 1.0.0 which [requires node 10.16.0](https://github.com/mscdex/busboy/issues/266)
this PR corrects the changelog to reflect this
> 📝 fix changelog information

- CHANGELOG.md
- package.json
- No functional changes compared to `2.0.0-rc.4`.
- Version bump to `3.0.0-alpha.1` due to a security release in the `1.x` line, ensuring compliance with Semantic Versioning.
**Full Changelog**: https://github.com/expressjs/multer/compare/v2.0.0-rc.4...v3.0.0-alpha.1-proposal
> Release: v3.0.0-alpha.1 

- .github/workflows/legacy.yml
- .github/workflows/test.yml
- CHANGELOG.md
- package.json
As with other packages, we support Node >=18 🙂 for this new version
> support node >=18

- lib/make-middleware.js
- package.json
Spread in object literals is natively supported in Node.js since v8.3.0. Minimum version of Node.js supported by multer at the moment is v10.16.0, so we should be good to go.
> chore: drop xtend dependency
